

export const PROJECTS = [
    {id: 1, 
        name: 'Testi1', 
        imgUrl: 'https://material.angular.io/assets/img/examples/shiba2.jpg', 
        imgAlt: '', 
        description: 'short descriptive text', 
        tools: ["C++", "QtCreator"], 
        details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eros tortor, consectetur at massa euismod, feugiat sollicitudin magna. Phasellus ligula turpis, ullamcorper venenatis tristique ac, molestie sed ipsum. Ut euismod nisi vel tincidunt fringilla. Nulla pharetra mattis maximus. Proin ornare malesuada sollicitudin. Nam eu iaculis nisi. Vivamus sit amet est id nisi suscipit consectetur. Ut turpis erat, bibendum sit amet ligula ac, ornare mollis sem.',
        extraimg: ['https://material.angular.io/assets/img/examples/shiba2.jpg', 'https://material.angular.io/assets/img/examples/shiba2.jpg']},
    {id: 2, 
        name: 'Testi2', 
        imgUrl: 'https://material.angular.io/assets/img/examples/shiba2.jpg', 
        imgAlt: '', 
        description: 'das',
        tools: ["C++", "QtCreator"],  
        details: ''},
    {id: 3, 
        name: 'Taysfiesta gamestore', 
        imgUrl: 'https://material.angular.io/assets/img/examples/shiba2.jpg', 
        imgAlt: '', 
        description: '', 
        tools: ["C++", "QtCreator"], 
        details: ''},
    {id: 4, 
        name: 'Galaxy Quest', 
        imgUrl: 'https://material.angular.io/assets/img/examples/shiba2.jpg', 
        imgAlt: '', 
        description: '', 
        tools: ["C++", "QtCreator"], 
        details: ''},
    {id: 5, 
        name: 'Portfolio sivut', 
        imgUrl: '', imgAlt: '', 
        description: '', 
        tools: ["C++", "QtCreator"], 
        details: ''},
    {id: 6, 
        name: 'IPv4 subnet calculator', 
        imgUrl: '', 
        imgAlt: '', 
        description: '', 
        tools: ["C++", "QtCreator"], 
        details: ''},
    {id: 7, 
        name: 'Joku unity projekti', 
        imgUrl: '', 
        imgAlt: '', 
        description: '', 
        tools: ["C++", "QtCreator"], 
        details: ''},
    {id: 8, 
        name: 'Realistinen 3d mallinnus projekti', 
        imgUrl: 'https://material.angular.io/assets/img/examples/shiba2.jpg', 
        imgAlt: '', 
        description: '', 
        tools: ["C++", "QtCreator"], 
        details: ''},
  ];